import { Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { HistoryPoint } from "../../types/currency";

type Props = { base: string; quote: string; period: number; data: HistoryPoint[]; loading: boolean; error: string | null; onPeriodChange: (period: number) => void };

export function RateHistoryCard({ base, quote, period, data, loading, error, onPeriodChange }: Props) {
  const periods = [{ label: "1 Day", value: 1 }, { label: "7 Days", value: 7 }, { label: "30 Days", value: 30 }];
  const chartData = data.map((point) => ({ ...point, label: point.date.slice(5) }));
  return <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition-colors dark:border-slate-700 dark:bg-slate-900 lg:p-8"><div className="flex flex-wrap items-center justify-between gap-4"><h2 className="text-lg font-semibold tracking-tight text-slate-900 dark:text-white">Exchange Rate History <span className="font-normal text-slate-400">({base} to {quote})</span></h2><div className="flex rounded-lg border border-slate-200 p-1 dark:border-slate-700">{periods.map((item) => <button key={item.value} onClick={() => onPeriodChange(item.value)} className={`rounded-md px-3 py-1.5 text-sm font-medium transition ${period === item.value ? "bg-blue-600 text-white shadow-sm" : "text-slate-600 hover:bg-slate-50 dark:text-slate-300 dark:hover:bg-slate-800"}`}>{item.label}</button>)}</div></div><div className="mt-8 h-64">{loading ? <div className="flex h-full items-center justify-center text-sm text-slate-400">Loading history…</div> : error ? <div className="flex h-full items-center justify-center text-sm text-rose-500">{error}</div> : chartData.length ? <ResponsiveContainer width="100%" height="100%"><LineChart data={chartData}><XAxis dataKey="label" tick={{ fontSize: 12, fill: "#94a3b8" }} axisLine={false} tickLine={false} /><YAxis domain={["auto", "auto"]} tick={{ fontSize: 12, fill: "#94a3b8" }} axisLine={false} tickLine={false} width={44} /><Tooltip formatter={(value) => [Number(value).toFixed(4), "Rate"]} labelFormatter={(label) => `Date: ${label}`} /><Line type="monotone" dataKey="rate" stroke="#2563eb" strokeWidth={3} dot={false} activeDot={{ r: 5 }} /></LineChart></ResponsiveContainer> : <div className="flex h-full items-center justify-center text-sm text-slate-400">No history data available.</div>}</div><p className="mt-5 text-center text-xs text-slate-400">Source: Frankfurter · Reference rates</p></div>;
}
